### ISSUE TITLE
Text Alingment, Domain Advice

### ISSUE THREAD

**Issue by NishithP2004** [BennyGodwinM/site#1]
Hey, 

I noticed that your site is currently hosted at https://bennygodwinm.github.io/site, Ideally if you would like to host further websites from a unified domain, it's recommended that you rename this repo to bennygodwinm.github.io so that this becomes the root of all the subdomains or repos which you may integrate with Github pages in the future.

Secondly, all the site content is floating towards the top-left corner.
(Refer ss)

![image](https://user-images.githubusercontent.com/34577844/113322730-b177d300-9332-11eb-9577-2c25d7fe7297.png)

**Comment by BennyGodwinM** [comment]
Thanks for the suggestion, can you please help in in centring the content of the website.

Regarding the domain, I aim to replace it with a professional one soon. I hope I will be able to do that with the current setup
